---

- name: Ensure external ingress state is {{ external_ingress_state }}
  kubernetes.core.helm:
    kubeconfig: "{{ external_ingress_kubeconfig }}"
    name: ingress-nginx
    chart_repo_url: "https://kubernetes.github.io/ingress-nginx"
    chart_ref: ingress-nginx
    release_namespace: "{{ external_ingress_namespace }}"
    release_state: "{{ external_ingress_state }}"
    chart_version: "{{ external_ingress_chart_version }}"
    create_namespace: "{{ external_ingress_create_namespace }}"
    values:
      controller:
        config:
          proxy-body-size: "{{ external_ingress_proxy_body_size }}"
        replicaCount: "{{ external_ingress_replica_count }}"
        minAvailable: "{{ external_ingress_min_available }}"
        service:
          type: NodePort
          nodePorts:
            http: "{{ external_ingress_http_port }}"
            https: "{{ external_ingress_https_port }}"
            tcp:
              8080: "{{ external_ingress_tcp_port }}"
