---
- name: Converge
  hosts: all
  gather_facts: false
  vars: 
  - external_ingress_kubeconfig: "~/.k3d/kubeconfig-$instance.yaml"
  tasks:
    - name: "Include neatleap.ensure_external_ingress_state"
      ansible.builtin.include_role:
        name: "ansible_role_ensure_external_ingress_state"
      delegate_to: localhost