---
- name: Converge
  hosts: localhost
  gather_facts: false
  vars: 
  - external_ingress_kubeconfig: ""
  tasks:
    - name: "Include garliclabs.ensure_external_ingress_state"
      ansible.builtin.include_role:
        name: "ansible_role_ensure_external_ingress_state"